version: "3"

# https://github.com/jpetazzo/dind

services:
  docker-in-docker:
    image: docker:dind
    privileged: true

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - docker-in-docker
    links:
      - docker-in-docker
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    volumes:
      - ..:/workspace:delegated
    command: sleep infinity
