version: "3"


services:
  nextools:
    container_name: "vscode-nextools"
    image: "vscode-nextools"
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      # https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx"
      - "$HOME/.gnupg/trustdb.gpg:/root/.gnupg/trustdb.gpg"
    command: "sleep infinity"
